custom: https://bagis.kizilay.org.tr/tr)  
custom: https://archive.org/donate/)  
  [Newgrounds](https://www.newgrounds.com/supporter)  
  [Linux Foundation](https://www.linuxfoundation.org/about/donate)
