custom: |
  [Kızılay](https://bagis.kizilay.org.tr/tr)  
  [Internet Archive](https://archive.org/donate/)  
  [Newgrounds](https://www.newgrounds.com/supporter)  
  [Linux Foundation](https://www.linuxfoundation.org/about/donate)
